0niel/university-app

- lib/common/calendar.dart
- lib/presentation/pages/schedule/components/schedule_page_view.dart
- test/calendar_test.dart
- test/mirea_test.dart
- Из календаря убраны константы. 
- Пофикшен баг в функции определения номера текущей недели
- Переделана функция получения дней в выбранной учебной неделе
- Создан класс для динамического получения даты начала семестра
- **Добавлены тесты!**
> Better calendar

- lib/main.dart
- lib/presentation/bloc/home_navigator_bloc/home_navigator_bloc.dart
- lib/presentation/pages/home/home_navigator_screen.dart
- lib/presentation/pages/onboarding/onboarding_screen.dart
- lib/presentation/pages/onboarding/widgets/next_button.dart
1. Исправлен возврат на страницу Intro экрана при первом запуске приложения.
2. Исправлена стартовая страница приложения. Теперь она на расписании и не переключается сразу после старта.
> FIX: bottom navigation bar

- lib/presentation/pages/schedule/widgets/autocomplete_group_selector.dart
> FEATURE: add group selector formatter

- lib/data/repositories/schedule_repository_impl.dart
> FIX: remove an error after deleting a group on API

- lib/presentation/bloc/map_cubit/map_cubit.dart
- lib/presentation/bloc/map_cubit/map_state.dart
- lib/presentation/pages/map/map_screen.dart
- lib/presentation/pages/map/widgets/map_scaling_button.dart
На основе: https://github.com/Ninja-Official/rtu-mirea-mobile/issues/55
Добавлено:
- Ограничение на максимальное приближение
- Ограничение на максимальное отдаление
- Кнопка для отображения текущего приближения, и возврата дефолтного значения приближения
- При клике на кнопку возвращается дефолтное значение приближения
Выгдядит вот так:
> Feature/scaling map feature #55

- lib/data/datasources/schedule_local.dart
- lib/data/models/schedule_settings_model.dart
- lib/data/repositories/schedule_repository_impl.dart
- lib/domain/entities/schedule_settings.dart
- lib/domain/repositories/schedule_repository.dart
- lib/domain/usecases/get_schedule_settings.dart
- lib/domain/usecases/set_schedule_settings.dart
- lib/domain/usecases/usecase.dart
- lib/presentation/bloc/schedule_bloc/schedule_bloc.dart
- lib/presentation/bloc/schedule_bloc/schedule_event.dart
- lib/presentation/bloc/schedule_bloc/schedule_state.dart
- lib/presentation/pages/schedule/schedule_screen.dart
- lib/presentation/pages/schedule/widgets/empty_lesson_card.dart
- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
- lib/presentation/widgets/settings_switch_button.dart
- lib/service_locator.dart
Созданы специальные юзкейсы для управления будущими настройками расписания, а также добавлена функция отображения пустых пар.
> FEATURE: create schedule settings buttons and add empty lessons

- lib/presentation/pages/schedule/widgets/lesson_card.dart
> FIX: increase maxLines to display more text

- lib/data/models/schedule_settings_model.dart
- lib/data/repositories/schedule_repository_impl.dart
- lib/domain/entities/schedule_settings.dart
- lib/presentation/bloc/schedule_bloc/schedule_bloc.dart
- lib/presentation/bloc/schedule_bloc/schedule_event.dart
- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
> FEATURE: add calendar type save

- lib/presentation/pages/news/news_screen.dart
> FIX: add news loading

- lib/presentation/pages/profile/about_app_page.dart
- lib/presentation/widgets/icon_button.dart
Довольно простое решение проблемы с кнопками - замена фиксированного размера (задаваемого через фиксированные отступы) на динамический размер через Expanded и SizedBox между кнопками. Так что и с низким, и с высоким разрешением экрана работает и выглядит нормально, изменения в коде минимальные и касаются только части кнопок
> FIX: make buttons in about page non-fixed size

- lib/presentation/pages/schedule/widgets/schedule_settings_modal.dart
- lib/presentation/widgets/keyboard_positioned.dart
Фиксит https://github.com/Ninja-Official/rtu-mirea-mobile/issues/79
В рамках PR добавлен переиспользуемая логика, при которой обьект поднимается на размер равный клавиатуры, тем самым поле ввода становится видным для пользователей:
(Поле ввода "ваша группа" теперь будет над клавиатурой для любых устройств):
> [FIX] FIX: input field keyboard fix

- lib/presentation/pages/onboarding/onboarding_screen.dart
Исправление неправильной пунктуации и улучшение текста на экране приветствия.
> FIX: punctuation on greeting screen

- lib/presentation/bloc/schedule_bloc/schedule_bloc.dart
> UX: remove evening lessons

- lib/data/datasources/strapi_remote.dart
- lib/data/models/story_model.dart
- lib/data/models/strapi_media_model.dart
- lib/data/repositories/strapi_repository_impl.dart
- lib/domain/entities/story.dart
- lib/domain/entities/strapi_media.dart
- lib/domain/repositories/strapi_repository.dart
- lib/domain/usecases/get_stories.dart
- lib/main.dart
- lib/presentation/bloc/stories_bloc/stories_bloc.dart
- lib/presentation/bloc/stories_bloc/stories_event.dart
- lib/presentation/bloc/stories_bloc/stories_state.dart
- lib/presentation/pages/news/news_screen.dart
- lib/presentation/pages/news/widgets/stories_wrapper.dart
- lib/presentation/pages/news/widgets/story_item.dart
- lib/service_locator.dart
- pubspec.yaml
На странице новостей сверху теперь отображаются сторисы, которые подтягиваются со Strapi CMS (cms.mirea.ninja)
> FEATURE: create stories on the news page

- lib/presentation/pages/news/news_details_page.dart
- lib/presentation/pages/news/widgets/news_item.dart
- pubspec.yaml
Анимация загрузки в виде `CircularProgressIndicator` заменена на слабый shimmer эффект.
> UX: update news image loading animation

- android/app/build.gradle
- android/app/src/main/kotlin/ninja/mirea/mireaapp/HomeWidgerProvider.kt
- android/app/src/main/kotlin/ninja/mirea/mireaapp/MainActivity.kt
- android/app/src/main/kotlin/ninja/mirea/mireaapp/widget_channel/HomeFactory2.kt
- android/app/src/main/kotlin/ninja/mirea/mireaapp/widget_channel/Models.kt
- android/app/src/main/kotlin/ninja/mirea/mireaapp/widget_channel/UpdateWidgetService.kt
- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
- lib/presentation/widgets/buttons/select_range_date_button.dart
Добавление возможности установления peer-to-peer и device-to-device соединения с другими устройствами с установленным приложением в условиях отсутствующего или плохого WiFi или мобильного интернета.
Реализовано с использованием NewNode ([https://github.com/clostra/newnode](https://github.com/clostra/newnode)).
> [FEATURE] Feature/newnode

- lib/data/datasources/user_remote.dart
- lib/main.dart
- lib/presentation/widgets/fullscreen_image.dart
- pubspec.yaml
Все зависимости были обновлены для работы с Flutter 2.8
> REFACTOR: update dependency versions

- lib/data/datasources/forum_remote.dart
- lib/domain/entities/forum_member.dart
> FIX: make ForumMember flairName nullable to avoid crash

- lib/presentation/pages/map/map_screen.dart
- lib/presentation/pages/map/widgets/map_scaling_button.dart
Изменены дефолтные проценты масштаба карты на то, как указано в #94
> FEATURE: update map scale values

- lib/presentation/bloc/about_app_bloc/about_app_bloc.dart
- lib/presentation/bloc/home_navigator_bloc/home_navigator_bloc.dart
- lib/presentation/bloc/news_bloc/news_bloc.dart
- lib/presentation/bloc/schedule_bloc/schedule_bloc.dart
- pubspec.yaml
Обновлена версия пакетов bloc, произведена миграция с v7.1.0 в v7.2.0 по гайду https://bloclibrary.dev/#/migration?id=packagebloc-1
Требуются ещё дополнительные наблюдения
> REFACTOR: migrate from bloc 7 to bloc 8 versions

- lib/data/datasources/strapi_remote.dart
- lib/data/models/story_model.dart
Обновлены fromJson методы для сторис т.к. нет совместимости с новой версией Strapi CMS.
> FIX: updated stories fromJson methods

- lib/common/calendar.dart
> FIX: changed the start date of the semester

- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
#139. Когда текущий день находится за рамками промежутка дней в календаре, то выбранный день не отображался. Добавлена валидация.
> FIX: added validation of the selected day in the calendar

- lib/presentation/pages/home_page.dart
#139. Исправлено перекрытие нижней навигации элементами интерфейса операционной системы
> UX: added SafeArea for BottomNavigationBar

- lib/data/models/strapi_media_model.dart
- lib/domain/entities/strapi_media.dart
- lib/presentation/bloc/news_bloc/news_bloc.dart
> FIX: removed news refresh when loading

- lib/presentation/pages/profile/profile_page.dart
#139. Индикаторы прогресса в профиле теперь по центру страницы
> UX: added centering the progress indicator in the profile

- lib/presentation/pages/profile/profile_announces_page.dart
#139. Ссылки на странице объявлений профиля теперь открывают браузер
> FIX: added onLinkTap action to the profile announces page

- lib/presentation/pages/news/widgets/stories_wrapper.dart
- lib/presentation/pages/profile/profile_attendance_page.dart
- lib/presentation/widgets/copy_text_block.dart
#139. Уменьшен размер картинки в сторис, добавлен отсуп у текста в профиле, изменены внутренние отступы у нижнего всплывающего информационного окна
> UX: added small UX improvements

- lib/presentation/core/routes/routes.dart
- lib/presentation/core/routes/routes.gr.dart
- lib/presentation/pages/home_page.dart
- lib/presentation/pages/news/widgets/stories_wrapper.dart
- lib/presentation/pages/news/widgets/story_item.dart
1. Исправлено #171 
2. Добавлен отступ от заголовка для текст у истории
3. Истории теперь открываются на весь экран (не вложены в страницу новостей)
4. Открытие и закрытие истории теперь происходит с Hero анимацией 
5. Истории теперь длятся немного дольше
> UX: update stories

- lib/presentation/pages/news/news_page.dart
Истории занимали много места. Добавлен `NestedScrollView` для того чтобы истории скрывались при скроллинге новостей
> UX: add stories hiding with scroll

- lib/presentation/pages/profile/profile_attendance_page.dart
> UX: update profile attendance button padding

- lib/data/datasources/strapi_remote.dart
- lib/data/models/update_info_model/update_info_model.dart
- lib/data/models/update_info_model/update_info_model.freezed.dart
- lib/data/models/update_info_model/update_info_model.g.dart
- lib/data/repositories/strapi_repository_impl.dart
- lib/domain/entities/update_info.dart
- lib/domain/repositories/strapi_repository.dart
- lib/domain/usecases/get_update_info.dart
- lib/presentation/bloc/update_info_bloc/update_info_bloc.dart
- lib/presentation/pages/home_page.dart
- lib/presentation/widgets/update_info_modal.dart
Теперь обновление проверяется по всему списку обновлений с помощью Build Number
> FEATURE: add build number check to update info

- lib/presentation/pages/profile/profile_lectors_page.dart
- test/mirea_test.dart
> UX: update lectors search bar width

- lib/presentation/pages/schedule/widgets/autocomplete_group_selector.dart
> FIX: update schedule group text formatter

- lib/presentation/bloc/scores_bloc/scores_bloc.dart
- lib/presentation/pages/profile/profile_scores_page.dart
- lib/presentation/pages/profile/widgets/scores_chart_modal.dart
- pubspec.yaml
Изменена страница зачетной книжки:
1. Теперь оценки отображаются в виде таблицы.
2. Добавлена цветовая индикация оценки.
3. Добавлена возможность просматривать график своего среднего балла по семестрам.
4. Добавлена сортировка семестров по возрастанию
> FEATURE: add a score table and average rating graph

- android/app/build.gradle
- android/app/src/main/kotlin/ninja/mirea/mireaapp/widget_channel/HomeWidgetPlugin.kt
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- lib/common/utils/calendar_utils.dart
- lib/data/repositories/forum_repository_impl.dart
- lib/data/repositories/github_repository_impl.dart
- lib/data/repositories/news_repository_impl.dart
- lib/data/repositories/schedule_repository_impl.dart
- lib/domain/repositories/app_settings_repository.dart
- lib/main.dart
- lib/presentation/bloc/news_bloc/news_bloc.dart
- lib/presentation/colors.dart
- lib/presentation/core/routes/routes.dart
- lib/presentation/pages/news/news_page.dart
- lib/presentation/pages/news/widgets/story_item.dart
- pubspec.yaml
- test/mirea_test.dart
Обновлены версии Gradle и Kotlin, исправлены ошибки зависимостей, возникающие при сборке с Flutter SDK v3.1
> refactor: Upgrade Flutter SDK and Kotlin version

- lib/presentation/pages/onboarding/widgets/next_button.dart
- lib/presentation/pages/schedule/schedule_page.dart
- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
- lib/presentation/pages/schedule/widgets/schedule_settings_drawer.dart
- pubspec.yaml
Обновлён Drawer страницы с расписанием. Теперь он имеет фиксированную максимальную ширину. Удалена зависимость [flutter_inner_drawer](https://github.com/0niel/flutter_inner_drawer)
> ui: Update Schedule page Drawer

- lib/presentation/pages/schedule/schedule_page.dart
Теперь страница расписания без активной группы отображает информацию о том, что нужно установить хотя бы одну группу для отображения календаря.
Fixed #238
> ui: Update empty Schedule page view

- lib/domain/entities/score.dart
- lib/presentation/pages/profile/profile_scores_page.dart
Новый списочный вид (с карточками) страницы оценок, добавлена кнопка переключения между видами. Сокращены названия оценок в таблице.
> ui: New type of scores view and shorten names

- lib/data/datasources/user_remote.dart
- lib/data/repositories/user_repository_impl.dart
- lib/presentation/bloc/auth_bloc/auth_bloc.dart
Удаление токенов при выходе, чтобы повторный вход не провоцировал загрузку токенов доступа из локального хранилища.
> fix: Remove tokens when logging out

- lib/presentation/pages/profile/widgets/scores_chart_modal.dart
Исправлено отображение графика успеваемости для некоторых студентов.
Неявка и долги теперь учитываются в среднем балле за семестр. Это решает проблему с отображением графика успеваемости для тех студентов, у которых не было оценок после прошедшей экзаменационной сессии.
> Include resit exams in a scores chart

- .github/workflows/main.yml
- .github/workflows/pre-release.yml
- .github/workflows/tests.yml
- lib/data/repositories/forum_repository_impl.dart
- lib/data/repositories/github_repository_impl.dart
- lib/data/repositories/news_repository_impl.dart
- lib/data/repositories/schedule_repository_impl.dart
- lib/data/repositories/strapi_repository_impl.dart
- lib/data/repositories/user_repository_impl.dart
- lib/firebase_options.dart
- lib/main.dart
- lib/presentation/core/routes/routes.gr.dart
- lib/presentation/pages/news/news_page.dart
- lib/presentation/widgets/buttons/settings_button.dart
- lib/service_locator.dart
- pubspec.yaml
Добавлена поддержка веб версии приложения (в браузере)
> feature: Add web support

- android/app/src/main/kotlin/ninja/mirea/mireaapp/HomeWidgerProvider.kt
- android/app/src/main/kotlin/ninja/mirea/mireaapp/widget_channel/HomeWidgetIntent.kt
Пофикшен баг из-за которого не работал виджет на Android.
До: 
https://user-images.githubusercontent.com/40907255/219377271-0985c730-300a-4916-8572-10a2a69e827b.mp4
После:
https://user-images.githubusercontent.com/40907255/219377501-93fda38e-ffb1-430f-b70e-e5320539760d.mp4
> fix: android widget

- lib/presentation/pages/profile/about_app_page.dart
При нажатии на версию теперь открывается подробная информация:
> ui: Add popup with build number

- lib/main.dart
Добавил логирование ошибок Bloc в Sentry
> feature: Create custom BlocObserver for Sentry

- lib/data/datasources/user_remote.dart
- lib/data/models/edu_program_model.dart
- lib/data/models/student_model.dart
- lib/data/models/user_model.dart
- lib/domain/entities/edu_program.dart
- lib/domain/entities/student.dart
- lib/domain/entities/user.dart
- lib/presentation/bloc/nfc_pass_bloc/nfc_pass_bloc.dart
- lib/presentation/bloc/user_bloc/user_bloc.dart
- lib/presentation/pages/profile/profile_detail_page.dart
- lib/presentation/pages/profile/profile_nfc_pass_page.dart
- lib/presentation/pages/profile/profile_page.dart
Теперь при наличии двух профилей (например, бакалавриат и магистратура), выбран будет только активный.
> fix: Select only active LKS profile

- lib/presentation/pages/profile/widgets/scores_chart_modal.dart
> ui: Update `ScoresChartModal` view

- lib/presentation/pages/map/map_page.dart
Добавлено увеличительное стекло на странице карты. Лупа отображается при зажатии 
https://user-images.githubusercontent.com/51058739/221030057-179584f1-209e-4cab-bd26-9d59812b4cfe.mp4
> ui: Add map magnifier

- lib/presentation/pages/profile/about_app_page.dart
* Удалены патроны и ссылки на Patreon
* Актуализированы ссылки на соц. сети
* Изменён текст. Добавлена благодарность Анне за помощь с картами
> ui: Update about app page

- assets/icons/social-sharing.svg
- lib/presentation/pages/profile/profile_scores_page.dart
- lib/presentation/pages/profile/widgets/scores_chart_modal.dart
- pubspec.yaml
* Добавил закругление углов для модального окна
* Исправлены отступы слева у первого столбца
* Добавлены линии тренда и переключения между ними
* Изменён внешний вид элементов легенды графика
https://user-images.githubusercontent.com/51058739/221354095-767240a8-e290-4c38-9bf1-37aea1565f91.mp4
> ui: Update scores chart modal

- README.md
- android/build.gradle
- assets/icons/social-sharing.svg
- lib/data/datasources/user_remote.dart
- lib/data/models/edu_program_model.dart
- lib/data/models/student_model.dart
- lib/data/models/user_model.dart
- lib/domain/entities/edu_program.dart
- lib/domain/entities/student.dart
- lib/domain/entities/user.dart
- lib/main.dart
- lib/presentation/bloc/nfc_pass_bloc/nfc_pass_bloc.dart
- lib/presentation/bloc/user_bloc/user_bloc.dart
- lib/presentation/pages/home_page.dart
- lib/presentation/pages/map/map_page.dart
- lib/presentation/pages/profile/about_app_page.dart
- lib/presentation/pages/profile/profile_detail_page.dart
- lib/presentation/pages/profile/profile_nfc_pass_page.dart
- lib/presentation/pages/profile/profile_page.dart
- lib/presentation/pages/profile/profile_scores_page.dart
- lib/presentation/pages/profile/widgets/scores_chart_modal.dart
- lib/presentation/pages/schedule/schedule_page.dart
- lib/presentation/widgets/feedback_modal.dart
- lib/service_locator.dart
- pubspec.yaml
* Обновлён график среднего балла на странице зачётной книжки. Добавлены линии тренда и переключения между ними (#290 и #295 от @0niel)
* Добавлено увеличительное стекло на странице карты. Лупа отображается при зажатии (#291 от @0niel)
* Изменена страница "О приложении". Удалены патроны и ссылки на Patreon, актуализированы ссылки. Изменён текст (#293 от @0niel)
* Добавлена интеграция с Sentry. Удалена зависимость Firebase Crashlytics (#287 и #289 от @0niel)
* Добавлены отзывы об ошибках на странице расписания и профиля (#292 от @0niel)
* Теперь при наличии двух профилей ЛКС (например, бакалавриат и магистратура), выбран будет только активный (#288 и #294 от @0niel)
* Добавлена документация переменных времени компиляции в README.md (#287 от @0niel)
> Release v1.3.1

- lib/data/datasources/user_remote.dart
- lib/data/repositories/user_repository_impl.dart
- lib/domain/repositories/user_repository.dart
- lib/domain/usecases/get_scores.dart
- lib/presentation/bloc/scores_bloc/scores_bloc.dart
- lib/presentation/bloc/scores_bloc/scores_event.dart
- lib/presentation/pages/profile/profile_scores_page.dart
* Исправлено #297
* Теперь оценки отображаются только для активного профиля ЛКС
> fix: Add displaying coursework in scores

- lib/common/utils/connection_checker.dart
- lib/data/repositories/forum_repository_impl.dart
- lib/data/repositories/github_repository_impl.dart
- lib/data/repositories/news_repository_impl.dart
- lib/data/repositories/schedule_repository_impl.dart
- lib/data/repositories/strapi_repository_impl.dart
- lib/data/repositories/user_repository_impl.dart
- lib/service_locator.dart
- pubspec.yaml
Исправлены проблемы, связанные с якобы отсутсутствием интернет соединения
> fix: Create new internet connection checker

- lib/common/utils/connection_checker.dart
- lib/data/datasources/user_local.dart
- lib/data/datasources/user_remote.dart
- lib/data/repositories/forum_repository_impl.dart
- lib/data/repositories/github_repository_impl.dart
- lib/data/repositories/news_repository_impl.dart
- lib/data/repositories/schedule_repository_impl.dart
- lib/data/repositories/strapi_repository_impl.dart
- lib/data/repositories/user_repository_impl.dart
- lib/domain/repositories/user_repository.dart
- lib/domain/usecases/get_scores.dart
- lib/presentation/bloc/scores_bloc/scores_bloc.dart
- lib/presentation/bloc/scores_bloc/scores_event.dart
- lib/presentation/pages/profile/profile_scores_page.dart
- lib/service_locator.dart
- pubspec.yaml
* Теперь оценки в отображаются только для активного профиля ЛКС (#298 от @0niel)
* Теперь отображаются оценки за курсовые работы (#298 от @0niel)
* Исправлены проблемы, связанные с якобы отсутсутствием интернет соединения (#300 от @0niel)
* Исправлена проблема, из-за которой требовалось постоянно авторизовываться через ЛКС при запуске (#301 от @0niel)
> Release v1.3.2

- lib/presentation/pages/map/map_page.dart
Больше нельзя получиться значения приближения на карте > 200% и < 0%
> ui: Fix max and min Map scale values

- lib/navigation/view/scaffold_navigation_shell.dart
- lib/onboarding/view/onboarding_page.dart
- lib/schedule/view/schedule_page.dart
- lib/schedule/widgets/settings_menu.dart
- pubspec.yaml
This reverts commit b0001aeb9223d5c215016dd3335b0f433c4c988e.
> Revert "feat: Vika integration"

- lib/profile/widgets/export_schedule_modal_content.dart
#413 
https://github.com/user-attachments/assets/53ebc16d-c24f-45d1-b692-3e7f6a2c9712
> feat: Add subjects selector to schedule exporter

- api/packages/rtu_mirea_schedule_api_client/lib/src/fields_data_parsers.dart
> fix: course project type

- ios/Flutter/AppFrameworkInfo.plist
- ios/Podfile
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Runner/AppDelegate.swift
> fix: ios build problem with YandexMobileAdsMediation

- api/Dockerfile
Добавлена возможность сборки Docker образа API непосредственно на сервере, без необходимости сборки артефакта на локальной машине.
> enh: added Dockerfile for API

- api/Dockerfile
В Dockrfile для API добавлены этапы установки Flutter SDK, необходимый для сборки образа.
> fix(api): added missing Flutter dependency in Dockerfile
