- lib/presentation/pages/schedule/widgets/schedule_settings_modal.dart
Высота модального окна выбора группы увеличена с 85% до 95%, т.к. на маленьких устройствах клавиатура может перекрывать inputbox.
> UX: update group selector modal window height

- lib/presentation/pages/schedule/schedule_screen.dart
После #74 надо было исправить параметр `schedule` метода `_buildGroupButton` в `lib/presentation/pages/schedule/schedule_screen.dart`, что собственно и [было сделано](https://github.com/Ninja-Official/rtu-mirea-mobile/commit/0540a8e2afa10d62c549d86e8679a003e88e808b) в первую очередь, а также задача не закрылась этим PR так как
> нужно дополнительно какое-то сообщение пользователю
Дополнительное сообщение сделано. Я немного поэксперементировал с интерфейсом и мне нравится 2 следующих варианта (первое - обычное состояние, когда есть доступ к интернету):
Мне лично больше нравится второй вариант - он [реализован](https://github.com/Ninja-Official/rtu-mirea-mobile/commit/21412c2f7e1b815087ad57e9a7c10b1e8b699150) в PR, здесь я использую тот же виджет, что используется в расписании для …
> FEATURE: schedule from cache indication

- lib/data/repositories/schedule_repository_impl.dart
- lib/domain/repositories/schedule_repository.dart
- lib/domain/usecases/get_schedule.dart
- lib/presentation/bloc/schedule_bloc/schedule_bloc.dart
- lib/presentation/bloc/schedule_bloc/schedule_state.dart
- lib/presentation/pages/schedule/schedule_screen.dart
- lib/presentation/pages/schedule/widgets/autocomplete_group_selector.dart
- lib/presentation/pages/schedule/widgets/schedule_settings_modal.dart
Исправлено #84. Теперь расписание по умолчанию загружается мгновенно из кэша, а обновляется в процессе уже потом. В репозиторий методу `getSchedule` был добавлен параметр `fromRemote`, который определяет, загружать ли расписание из удалённого репозитория или локального.
Чтобы не замедлять запуск, список всех групп загружается асинхронно при старте и теперь представляет из себя статическое публичное поле в ScheduleBloc, а не поле в состоянии ScheduleLoaded. Таким образом, не нужно будет обновлять состояние после загрузки расписания.
Поле `groups` убрано из состояния ScheduleLoaded.
> FIX: schedule loading from internet on start

- lib/common/calendar.dart
- lib/presentation/bloc/schedule_bloc/schedule_bloc.dart
- lib/presentation/bloc/schedule_bloc/schedule_event.dart
- lib/presentation/pages/schedule/schedule_screen.dart
- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
- lib/service_locator.dart
1. Если расписание загружено из кэша, но было обновлено в процессе, то состояние расписания (isRemote) теперь тоже обновляется.
2. Список предметов теперь получается не для целой недели, а для конкретного дня. То есть теперь расписание резко не меняется при смене недели, как это показано на видео ниже.
https://user-images.githubusercontent.com/51058739/132543110-d40f25bf-9e01-470e-a89a-3c1735175a36.MP4
> FIX: build schedule in next week and from cache

- lib/presentation/bloc/schedule_bloc/schedule_bloc.dart
- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
Хотфикс, который исправляет баг для магистратуры. Вечерние пары не отображались при включенном отображении пустых пар.
> FIX: add displaying evening lessons

- lib/presentation/pages/schedule/widgets/autocomplete_group_selector.dart
Исправлено #58 и #85. Рестарт метода ввода теперь не мешает форматировать группу по шаблоную
> FIX: avoid input method restarting in formatter

- .github/workflows/tests.yml
- android/app/src/main/kotlin/ninja/mirea/mireaapp/HomeWidgerProvider.kt
- android/app/src/main/kotlin/ninja/mirea/mireaapp/widget_channel/HomeFactory2.kt
- android/app/src/main/kotlin/ninja/mirea/mireaapp/widget_channel/UpdateWidgetService.kt
- android/app/src/main/res/xml/timetable_widget.xml
- lib/common/widget_data_init.dart
Список предметов не перезагружался при выборе новой группы. Это было вызвано тем, что фабрика списка предметов не обновлялась, т.к. считала интент не уникальным. Теперь он будет уникальным каждый раз, потому что его тип задаётся случайным образом.
```
val adapter = Intent(context, UpdateWidgetService::class.java)
val random = Random()
intent.type = (random.nextInt(2281337)).toString()
```
Демонстрация обновления списка предметов при выборе новой группы:
https://user-images.githubusercontent.com/62698748/145442958-ac173594-eff0-4102-bbbe-d284adb2fc6d.mp4
> FIX: Home widgets logic based on random

- android/app/src/main/kotlin/ninja/mirea/mireaapp/HomeWidgerProvider.kt
- lib/common/calendar.dart
- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
Приложение открывалось, зависало и вылетало.
К ошибке приводил код, который пытался получить текущую учебную неделю. Но семестр то ещё не начался, поэтому он бесконечно считал начиная с первого дня следующего семестра до момента переполнения DateTime и вылета приложения.
Что сделано:
- Возврат 1 недели, если семестр ещё не начался
- Дополнительная валидация _focusDate в календаре
- Фикс ошибки виджета, если в weekData находится null
> FIX: Critical calendar error

- lib/presentation/bloc/schedule_bloc/schedule_bloc.dart
Добавлено ожидания асинхронного вызова `fold` метда для предотвращения ошибки:
```
E/flutter ( 1751): emit was called after an event handler completed normally.
E/flutter ( 1751): This is usually due to an unawaited future in an event handler.
E/flutter ( 1751): Please make sure to await all asynchronous operations with event handlers
E/flutter ( 1751): and use emit.isDone after asynchronous operations before calling emit() to
E/flutter ( 1751): ensure the event handler has not completed.
```
> FIX: added an emit call after the event handler

- lib/presentation/pages/news/news_details_page.dart
#139. В деталях важных новостей пустая иконка тегов больше не отображается
> UX: hide an empty list of tags in the news

- lib/presentation/pages/schedule/schedule_page.dart
Убрано ненужное пространство снизу у BottomNavigationBar на странице расписания
> UX: fix the bottom indentation on the schedule page

- lib/presentation/pages/news/news_page.dart
Исправлено #158. Теперь окно тегов не открывается во время загрузки новостей
> FIX: delete dialog opening while news loading

- lib/common/utils/calendar_utils.dart
Теперь переключение на первый семестр учебного года происходит после 25-го августа, т.к. в конце августа публикуют документы с расписанием.
> fix: Update first semester start date

- android/app/src/main/AndroidManifest.xml
Приложения, ориентированные на Android 12 и выше требуют явного указания значения для `android:exported` (https://developer.android.com/guide/topics/manifest/activity-element#exported)
> fix(android 12): Add explicit value for `android:exported`

- lib/data/datasources/user_remote.dart
- lib/presentation/pages/home_page.dart
- lib/presentation/pages/profile/profile_page.dart
- lib/presentation/pages/profile/profile_scores_page.dart
У нижней навигационной панели не было цвета, что хорошо заметно на страницах, у которых фон отличается от стандартного. Например, на странице карты навигационная панель просвечивалась.
Было:
Стало:
> ui: Add Bottom Navigation Bar Background

- .github/workflows/main.yml
- .github/workflows/pre-release.yml
- .github/workflows/tests.yml
- lib/data/models/strapi_media_model.dart
- lib/domain/entities/story.dart
- lib/domain/entities/strapi_media.dart
- lib/presentation/pages/news/news_details_page.dart
- lib/presentation/pages/news/widgets/news_item.dart
- lib/presentation/pages/news/widgets/stories_wrapper.dart
- lib/presentation/pages/news/widgets/story_item.dart
- lib/presentation/widgets/images_horizontal_slider.dart
- pubspec.yaml
Не все типы изображений могут быть оптимизированы. Например, svg изображения не форматируются, поэтому formats у них возвращается null.
> fix: Add nullable image formats from CMS

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/xml/backup_rules.xml
По умолчанию Android создает резервные копии данных на Google Диске. Это может вызвать исключение `java.security.InvalidKeyException:Failed to unwrap key` при использовании Secure Storage.
> fix: Disable Secure Storage Android backups

- lib/main.dart
Теперь цвет навбара на Android совпадает с остальным интерфесом.
До: 
После:
> ui: fix navbar color

- lib/presentation/pages/profile/about_app_page.dart
- lib/presentation/pages/schedule/schedule_page.dart
- lib/presentation/widgets/feedback_modal.dart
Добавлены отзывы об ошибках на странице расписания и профиля. Отзывы используют Sentry User Feedback API.
* Если пользователь вошел с помощью ЛКС, то поля email будут иметь автозаполнение с помощью данных аккаунта ЛКС. 
* Если пользователь имеет активную группу расписания, то текст отзыва на странице будет иметь автозаполнение с учётом выбранной группы.
> feature: Add feedback modals

- lib/data/datasources/user_remote.dart
- lib/presentation/pages/profile/profile_attendance_page.dart
- lib/presentation/pages/profile/widgets/attendance_card.dart
* Карточки посещаемости теперь группируются по дате. Используется первая дата входа и последняя дата выхода.
* Посещаемость сортируется  по дате от самой новой.
* Исправлена ошибка, связанная с отсутствием в посещаемости записи о входе или выходе.
* Исправлена иконка выхода.
**Было:**
<details>
<summary>Скриншот</summary>
</details>
**Стало:**
<details>
<summary>Скриншот</summary>
</details>
> ui: Update attendance and fix null-error

- lib/presentation/pages/schedule/widgets/lesson_card.dart
- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
* Добавлен небольшой отступ для типа предмета в карточке расписания, чтобы текст не соприкасался с лейблом типа предмета
* Уменьшен размер круговых индикаторов календаря, чтобы они не соприкасались с индикаторами событий
> ui: Add types padding and update indicators sizes

- lib/presentation/pages/profile/profile_detail_page.dart
- lib/presentation/widgets/badged_container.dart
> ui: Fix status text overflow in profile

- lib/presentation/pages/schedule/widgets/schedule_page_view.dart
> fix: Display only unique calendar lesson events

- lib/common/utils/schedule_utils.dart
Насколько я понял, настройка с номером пары - легаси, поэтому таким образом легко фиксится текущее невалидное отображение пустых пар. А еще местами поменял, потому что так они вроде в порядке времени начала пары отсортированы
> fix: invalid view of empty lessons

- lib/presentation/widgets/images_view_gallery.dart
В #217 есть 3 пункта:
Свайпы вверх/вниз для выхода из показа фотографии на весь экран с [текущей библиотекой ](https://pub.dev/packages/photo_view) добавить нельзя - https://github.com/bluefireteam/photo_view/issues/265
> feature: add min/max zoom limit for photos in news

- api/packages/rtu_mirea_schedule_api_client/lib/src/fields_data_parsers.dart
Изменился формат сокращений в rtu_mirea_schedule_api_client. Добавлена проверка сокращенного варианта "З" для зачёта и "Э" для экзамена .
> fix: lesson type check, add support shorthand notation for lessonType
